version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: cron
      cronjob: '0 4 * * 6'
      timezone: Europe/Berlin
    groups:
      version-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    cooldown:
      semver-minor-days: 7
      semver-patch-days: 1
